// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fish.Migrations
{
    [DbContext(typeof(FishContext))]
    [Migration("20220119132038_FamilyModel")]
    partial class FamilyModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Fish.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("Fish.Models.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenusForeignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("GenusForeignId");

                    b.ToTable("Genus");
                });

            modelBuilder.Entity("Fish.Models.Genus", b =>
                {
                    b.HasOne("Fish.Models.Family", null)
                        .WithMany("genera")
                        .HasForeignKey("FamilyId");

                    b.HasOne("Fish.Models.Genus", "GenusForeign")
                        .WithMany()
                        .HasForeignKey("GenusForeignId");

                    b.Navigation("GenusForeign");
                });

            modelBuilder.Entity("Fish.Models.Family", b =>
                {
                    b.Navigation("genera");
                });
#pragma warning restore 612, 618
        }
    }
}
